buildscript {
    repositories {
        google()
        mavenCentral()
        maven {
            url "https://chaquo.com/maven" //? For executing python
        }
    }
    dependencies {
        classpath "com.android.tools.build:gradle:9.3.2"
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:2.1.21-RC2"
        classpath "com.chaquo.python:gradle:17.0.0"
    }
}